### ISSUE TITLE
Why do we need social media

### ISSUE THREAD

**Issue by AmazingMech2418** [Waffleprograming/Waffle-socialmedia#1]
I'm personally not a fan of social media. Why do we even need it?

**Comment by radioblahaj** [comment]
to advertise, scratch does.

**Comment by radioblahaj** [comment]
I wrote it 1 minute ago

**Comment by AmazingMech2418** [comment]
OK. Why do we need advertising before we even have a basic editor?

**Comment by radioblahaj** [comment]
I want to talk about the prouct. we need a designer, UI,  vuton is joining us

**Comment by AmazingMech2418** [comment]
Product? We don't have a product yet. We have a few JavaScript programs and a few test websites.

**Comment by Wiffi** [comment]
I Know!
Reply via @Waffleprograming/waffle-bots 
The Bot for All Waffle
